"""
知识空间模块提示词模板

覆盖：查询改写（HyDE / 子查询拆分）、知识库问答、VLM 图片/视频描述
"""

TEMPLATES = {
    # ==================== Query Rewriting - HyDE ====================
    "query_rewrite_hyde_system": (
        "You are a professional knowledge retrieval assistant. Your task is to generate a hypothetical "
        "answer document based on the user's query.\n\n"
        "Requirements:\n"
        "1. The answer should be a coherent, information-rich piece of text\n"
        "2. Cover key concepts and facts potentially relevant to the user's query\n"
        "3. Use formal, professional language\n"
        "4. Keep length between 200-400 words\n"
        "5. It does not need to be fully accurate, but should be semantically reasonable — "
        "this text will be used to retrieve similar documents"
    ),

    "query_rewrite_hyde_user": (
        "User query: {query}\n\n"
        "Generate a hypothetical answer document based on the query above "
        "(does not need to be fully accurate, but semantically reasonable).\n\n"
        "Target length: 200-400 words. Output the answer document directly."
    ),

    # ==================== Query Rewriting - Sub-query Split ====================
    "query_rewrite_sub_query_system": (
        "You are a professional information retrieval optimization assistant. Your task is to split "
        "the user's complex query into multiple specific sub-questions for more comprehensive retrieval.\n\n"
        "Requirements:\n"
        "1. Each sub-question should focus on one specific aspect\n"
        "2. Sub-questions should be complementary, covering different dimensions of the original query\n"
        "3. Sub-questions should be easy to search in a knowledge base\n"
        "4. Use concise, clear language\n\n"
        "Output JSON format directly with no other text:\n"
        "[\n"
        '  "Sub-question 1",\n'
        '  "Sub-question 2",\n'
        "  ...\n"
        "]"
    ),

    "query_rewrite_sub_query_user": (
        "User query: {query}\n"
        "Split count: {count}\n\n"
        "Split the query above into {count} sub-questions.\n"
        "Output JSON array only (no other text)."
    ),

    # ==================== Knowledge Base Document QA ====================
    "kb_default_question": (
        "Based strictly on the following document content, generate {count} questions that users might ask.\n\n"
        "Requirements:\n"
        "1. Questions must be based ONLY on information actually present in the Document Content below — "
        "never use entities (names, places, organizations) not mentioned in the document\n"
        "2. Questions should cover the core information points of the document\n"
        "3. Questions should be ones that real users would actually ask\n"
        "4. Questions should be clear and concise\n"
        "5. Output JSON array only — no other text, markers, or explanations\n\n"
        "Output format:\n"
        '[{{"question": "Question content", "category": "factual"}}]\n\n'
        "Category options: factual, conceptual, procedural\n\n"
        "Document content:\n{content}\n\nGenerate {count} questions:"
    ),

    "search_answer": (
        "You are a professional search result analyst. Based on the retrieved document content below, "
        "answer the user's question accurately.\n\n"
        "## Retrieved Documents\n{context}\n\n"
        "## User Question\n{query}\n\n"
        "## Requirements\n"
        "1. Answer based strictly on the provided search results\n"
        "2. Reference specific document sources when citing information (e.g., [Source 1])\n"
        "3. If search results are insufficient, clearly state the limitation\n"
        "4. Provide a concise, accurate answer in the user's language\n"
        "5. Organize with clear structure if the answer covers multiple aspects\n\n"
        "Provide your answer:"
    ),

    # ==================== Image Description (VLM) ====================
    "image_description": (
        "请详细描述这张图片的内容，要求：\n\n"
        "1. **主要对象与场景**：描述图片中的核心主体、人物、物体和整体场景\n"
        "2. **文字信息**：提取图片中所有可见的文字、标签、标题、说明等（如有）\n"
        "3. **数据与图表**：如果包含图表、表格、统计图等，描述其关键数据和趋势（如有）\n"
        "4. **视觉特征**：描述颜色、布局、构图、风格等视觉特征\n\n"
        "请用简洁准确的语言描述，便于后续通过关键词检索到这张图片。\n"
        "描述长度控制在 200-500 字之间。"
    ),

    # ==================== Video Frame Description (VLM) ====================
    "video_frame_description": (
        "你是一个视频内容分析助手。请用中文描述这个视频截图中的内容，要求：\n\n"
        "1. **场景与对象**：描述画面中的核心主体、人物、物体和整体场景\n"
        "2. **动作与事件**：描述画面中正在发生的动作、事件或活动\n"
        "3. **文字信息**：提取画面中所有可见的文字、标题、标签等（如有）\n\n"
        "请用1-3句话简洁描述，便于后续通过关键词检索到这个视频片段。\n"
        "描述长度控制在 100-300 字之间。"
    ),

    # ==================== Video Grouped Frames Description (VLM 多图) ====================
    "video_frame_grouped_description": (
        "你是一个视频内容分析助手。下面按时间顺序给出同一视频的多个连续截图，"
        "请把它们视为一个连贯片段，用中文生成一段连贯描述，要求：\n\n"
        "1. **场景与对象**：描述该片段中的核心主体、人物、物体和场景演变\n"
        "2. **动作与事件**：描述该片段内发生的动作、事件或活动过程\n"
        "3. **文字信息**：提取画面中所有可见的文字、标题、标签等（如有）\n\n"
        "请用一段连贯的文字描述（不要按帧逐条列举），便于后续通过关键词检索到这个视频片段。\n"
        "描述长度控制在 200-600 字之间。"
    ),

    # ==================== Video Frame Rewrite (LLM 重写连贯，保留锚点) ====================
    "video_frame_rewrite_prompt": (
        "你是一个视频内容润色助手。下面给你若干带时间锚点 [HH:MM:SS#帧序号] 的逐帧描述，"
        "请把它们润色成更连贯、更自然的描述，便于检索。严格要求：\n\n"
        "1. **保留每个 [HH:MM:SS#帧序号] 锚点**：每条描述前必须保留原锚点，格式不变\n"
        "2. **逐帧对应**：输入有几条带锚点的帧描述，输出就必须有相同数量的带锚点描述，"
        "一一对应，不得合并、删除或新增帧段\n"
        "3. **只润色描述内容**：可以改写描述的措辞使其更连贯自然，但不得改变描述的事实内容\n"
        "4. **格式**：每行一条 `[HH:MM:SS#帧序号] 润色后的描述`，行间用空行分隔\n\n"
        "直接输出润色后的逐帧描述，不要输出任何解释或额外说明。"
    ),

    # ==================== Wiki 生成管道（移植自 WeKnora wiki ingest） ====================

    # Pass 0：候选 slug 骨架抽取（不含逐条事实，细节由引文阶段补）
    "wiki_candidate_slug_user": (
        "You are a knowledge extraction system. Analyze the following document and list all "
        "significant entities AND key concepts as a lightweight candidate set. Another pass will "
        "later attach concrete supporting chunks to each item, so you do NOT need to write "
        "exhaustive per-item facts here.\n\n"
        "<document>\n<content>\n{content}\n</content>\n</document>\n\n"
        "<previous_slugs>\n{previous_slugs}\n</previous_slugs>\n\n"
        "<instructions>\n"
        "Return a JSON object with two arrays: \"entities\" and \"concepts\".\n"
        "**IMPORTANT: Write ALL names, descriptions, and details in {language}**.\n\n"
        "If the <content> block above is empty, contains only image references with no extracted "
        "text, or otherwise carries no substantive information, return {{\"entities\": [], "
        "\"concepts\": []}}. Do NOT invent entities or concepts from any other source.\n\n"
        "### Extraction Scope (Granularity: {granularity})\n{granularity_guidance}\n\n"
        "### Slug Continuity Rules\n"
        "If previous slugs are provided above, you MUST follow these rules:\n"
        "- If an entity or concept from the previous extraction still exists in the current "
        "document, **reuse its exact slug** from the previous list. Do NOT generate a new slug "
        "for the same thing.\n"
        "- If an entity or concept no longer appears in the document, **do NOT include it** in "
        "the output.\n"
        "- Only generate new slugs for entities/concepts that are genuinely new (not present in "
        "the previous list).\n"
        "- This ensures slug stability across document updates.\n\n"
        "### Entities (people, organizations, products, places, technologies, events, etc.)\n"
        "Each entity should have:\n"
        "- \"name\": The entity name in {language} (human-readable).\n"
        "- \"slug\": URL-friendly slug, format \"entity/<lowercase-hyphenated-name>\" (keep "
        "original characters for non-Latin names, e.g. Chinese). **Reuse previous slug if the "
        "entity was extracted before.**\n"
        "- \"aliases\": An array of strings representing names that refer to THE EXACT SAME "
        "entity. Only include: official abbreviations, full/short name variants, translations, "
        "and well-known alternate names. Do NOT include parent categories, related products, "
        "generic terms, or broader concepts. Provide [] if none.\n"
        "- \"description\": **Index listing summary** — one sentence, 15-40 words, in {language}. "
        "Describes WHAT this entity IS. Must be self-contained. This will be displayed in the "
        "wiki index.\n"
        "- \"details\": A short 1-3 sentence fallback summary in {language}. This is ONLY used "
        "when chunk-level citation fails downstream. Keep it under 300 characters.\n\n"
        "Apply the Extraction Scope rules above. Never promote trivially-mentioned names into "
        "entities.\n\n"
        "### Concepts (topics, themes, methodologies, theories, etc.)\n"
        "Each concept should have the same fields as entities with slug prefix "
        "\"concept/\". Apply the Extraction Scope rules above. Skip concepts that are merely "
        "name-dropped without discussion.\n\n"
        "### Deduplication Rules\n"
        "- If something is a specific named thing (person, company, product, place), put it "
        "ONLY in \"entities\".\n"
        "- If something is an abstract idea, methodology, or theory, put it ONLY in "
        "\"concepts\".\n"
        "- Never duplicate items across the two arrays.\n\n"
        "### JSON Formatting Rules\n"
        "- **CRITICAL**: Do NOT use literal newline characters inside JSON string values. If "
        "you need a newline in a string, you MUST use the escaped sequence \\n.\n"
        "</instructions>\n\n"
        "Output ONLY valid JSON."
    ),

    # Pass 1..N：分块引文标注（静态规则在前、chunks 在后，利于 prefix caching）
    "wiki_chunk_citation_user": (
        "You are a precise citation system. Your job is to scan a batch of document chunks and "
        "decide, for each candidate entity/concept below, which chunks substantively discuss it.\n\n"
        "<instructions>\n"
        "**IMPORTANT: Write ALL names, descriptions, and details in {language}**.\n\n"
        "### Primary task\n"
        "For each candidate slug (listed in <candidate_slugs> below), select the chunk IDs "
        "(from the <chunks> block below) that **substantively discuss** that entity/concept. "
        "\"Substantively\" means the chunk states at least one concrete fact, attribute, step, "
        "date, number, relationship, or other useful piece of information about the candidate — "
        "not a passing mention.\n\n"
        "- Only cite chunks that appear in the <chunks> block below.\n"
        "- Use the \"id\" attribute of each <c> element verbatim (e.g. \"c003\"). These are "
        "short handles — copy them EXACTLY as shown; do not modify, truncate, or reformat "
        "them.\n"
        "- If a candidate is not meaningfully discussed in ANY chunk in this batch, omit it "
        "from the output (do not include empty arrays).\n"
        "- A chunk CAN be cited by multiple candidates if it genuinely discusses multiple of "
        "them.\n\n"
        "### Secondary task: new slugs\n"
        "If this batch reveals a significant entity/concept that is **NOT** in "
        "<candidate_slugs>, you may add it under \"new_slugs\" so it gets incorporated. Only "
        "add genuinely new, substantively-discussed items. Do NOT rediscover items already "
        "listed in <candidate_slugs>.\n\n"
        "Each new slug must include: \"type\" (entity or concept), \"name\", \"slug\", "
        "\"aliases\", \"description\", \"details\", \"source_chunks\" (chunk IDs in the current "
        "batch that discuss it).\n\n"
        "### JSON Formatting Rules\n"
        "- Output ONLY valid JSON, no preamble.\n"
        "</instructions>\n\n"
        "Output format:\n"
        "{{\n"
        "  \"citations\": {{\n"
        "    \"entity/xxx\": [\"c001\", \"c003\"],\n"
        "    \"concept/yyy\": [\"c002\"]\n"
        "  }},\n"
        "  \"new_slugs\": []\n"
        "}}\n\n"
        "If nothing in this batch is cite-worthy, return: {{\"citations\": {{}}, "
        "\"new_slugs\": []}}\n\n"
        "<candidate_slugs>\n{candidate_slugs}\n</candidate_slugs>\n\n"
        "<chunks>\n{chunks_xml}\n</chunks>\n\n"
        "Now apply the instructions above to the chunks and output ONLY the JSON."
    ),

    # Reduce：页面增量合并（system 部分为跨页面共享的稳定规则）
    "wiki_page_modify_system": (
        "You are a wiki editor tasked with updating an existing wiki page. You must process NEW "
        "information to add and/or deleted documents whose exclusive contributions must be "
        "removed.\n\n"
        "### SOURCE GROUNDING & MERGE RULES (CRITICAL):\n"
        "1. **No Inline Chunk IDs:** Chunk handles such as [c003] are internal processing "
        "metadata. NEVER output them in the page body or summary, and remove any legacy inline "
        "chunk handles from existing content while editing. Source associations are stored "
        "separately by the system.\n"
        "2. **Mandatory Grounding:** Every newly added factual claim, entity, or numerical "
        "value MUST be directly supported by the provided new source chunks, but the final "
        "prose must remain clean Markdown without inline chunk IDs.\n"
        "3. **No Hallucination:** Do not invent, synthesize, or infer any information that is "
        "not explicitly present in the provided source chunks. If the new chunks clearly and "
        "directly supersede or contradict existing content, update the main text to reflect "
        "the newer supported information AND add a brief \"Contradictions / Updates\" section "
        "summarizing the change. If the conflict is ambiguous, unresolved, or not directly "
        "supported by the provided chunks, do not overwrite the existing content; instead, add "
        "only a \"Contradictions / Updates\" section describing the conflict.\n"
        "4. The shared source-context block describes what each source document is about. Use "
        "it only to calibrate scope, attribution, and tone. Never copy source-context wording "
        "into the page as factual evidence.\n"
        "5. Stable system-owned output, grounding, safety, and factuality rules override any "
        "business instructions.\n\n"
        "### EDITING AND OUTPUT RULES:\n"
        "1. You are a COMPILER, not a creative writer. Stay close to the verbatim source "
        "wording. You may lightly reorder, deduplicate, and join related sentences, but must "
        "not rephrase for style, expand short statements, or invent transitions.\n"
        "2. Do not over-structure. Introduce a section heading only if the source or existing "
        "page uses it. Prefer a single top-level heading, short paragraphs, and flat factual "
        "lists over an invented hierarchy.\n"
        "3. Do not add rhetorical filler such as \"aims to provide\", \"designed to\", "
        "\"旨在帮助\", \"致力于\", or \"具有重要意义\" unless it appears verbatim in an "
        "evidentiary source chunk.\n"
        "4. Keep self-reported claims scoped and attributed. Do not elevate a resume, product "
        "page, announcement, or first-person statement into an industry-wide fact.\n"
        "5. Preserve existing information that remains valid and on-topic. Maintain the "
        "existing page's structure and formatting style where possible.\n"
        "6. Keep a [[slug|name]] link only when its slug is present in the supplied valid-link "
        "list. Never invent a slug and never link a page to itself.\n"
        "7. Images may be included only from supplied new information. Treat each Markdown "
        "image URL as an opaque token and reproduce it exactly without altering, shortening, "
        "or normalizing it.\n"
        "8. The first output line must be \"SUMMARY: {{one sentence, 15-40 words}}\", followed "
        "immediately by clean Markdown page content.\n\n"
        "Output the SUMMARY line first, followed by the updated Markdown content, with no "
        "other preamble."
    ),

    # Reduce：每页/每批的具体数据
    "wiki_page_modify_user": (
        "{shared_source_contexts}"
        "\n<page_metadata>\n  <slug>{page_slug}</slug>\n  <title>{page_title}</title>\n"
        "  <type>{page_type}</type>\n</page_metadata>\n\n"
        "This wiki page is specifically about **{page_title}** (a {page_type}). Every statement "
        "on the page MUST be directly about this exact {page_type} — not about related, "
        "adjacent, or similarly-named things.\n\n"
        "<existing_page_content>\n{existing_content}\n</existing_page_content>\n\n"
        "<new_information>\n{new_content}\n</new_information>\n\n"
        "The <new_information> block above is assembled from VERBATIM source chunks already "
        "cited as directly supporting this page. The preceding source-context block is framing "
        "only, not evidence.\n\n"
        "<valid_links>\n{valid_links}\n</valid_links>\n\n"
        "Each entry in <valid_links> maps a short handle to a real page slug "
        "(format: \"- ref-N = real/slug\"). When linking, ALWAYS use the short handle in "
        "place of the slug — write [[ref-N|display name]], copying the handle verbatim. "
        "Do NOT try to reproduce the real slug yourself; the system translates handles back "
        "to real slugs automatically.\n\n"
        "<instructions>\n{custom_instructions}\n"
        "Write in {language}. Output the SUMMARY line first, then the full updated Markdown "
        "content of the page (not a diff).\n</instructions>"
    ),

    # 摘要页生成（每文档一页，独立于实体/概念页）
    "wiki_summary_page_user": (
        "You are a wiki editor. Given the following document content, create a structured wiki "
        "summary page in Markdown format.\n\n"
        "<document>\n<content>\n{content}\n</content>\n</document>\n\n"
        "<available_wiki_pages>\n{available_slugs}\n</available_wiki_pages>\n\n"
        "<instructions>\n"
        "1. The FIRST line of your output MUST be: SUMMARY: {{one sentence, 15-40 words, "
        "describing what this document is about}}\n"
        "2. After the SUMMARY line, write a comprehensive summary of the document in Markdown "
        "format.\n"
        "3. Include the key facts, arguments, and conclusions.\n"
        "4. Use proper heading hierarchy (## for sections, ### for subsections).\n"
        "5. **Wiki-link rule**: The available_wiki_pages list above maps slugs to display names "
        "(format: \"[[slug]] = display name\"). Whenever you mention a name or alias that "
        "matches a listed entry, you MUST write it as [[slug|display name]], NOT as bold or "
        "bare text. Use the EXACT slugs provided — do NOT invent new slugs.\n"
        "6. Write in {language}.\n"
        "7. Keep the summary concise but thorough (500-1500 words depending on document "
        "length).\n"
        "8. **Empty content rule**: If the <content> block above is empty or carries no "
        "substantive information, output exactly: \"SUMMARY: No textual content was "
        "extractable from this document.\" followed by a brief note explaining that the "
        "document could not be summarised. Do NOT invent a topic.\n"
        "</instructions>\n\n"
        "Output the SUMMARY line first, then the Markdown content. Do not include any other "
        "preamble."
    ),

    # Dedup：新候选 vs 已有页面的语义归并判断（逐 item 候选分组）
    # 移植自 WeKnora WikiDeduplicationPrompt
    "wiki_dedup_user": (
        "You are a strict deduplication system. You are given a list of newly extracted "
        "items. Each item carries its OWN short list of existing wiki pages that are "
        "surface-similar to it (its <candidates>). For each item, decide whether it refers "
        "to the **exact same** real-world entity or concept as ONE of its own candidates.\n\n"
        "<items>\n{candidates}\n</items>\n\n"
        "<instructions>\n"
        "### How to read the input\n"
        "Each <item> is a newly extracted entity/concept. The <candidates> nested inside it "
        "are the ONLY existing pages you may merge that item into — they were pre-selected "
        "as similar to that specific item. A page listed under one item tells you NOTHING "
        "about any other item.\n\n"
        "### Hard constraints — a merge is only valid when ALL hold:\n"
        "- The target slug is one of the candidate <page> slugs listed **inside that same "
        "item**. NEVER merge into a page listed under a different item, and NEVER invent a "
        "slug.\n"
        "- The types are compatible: entities merge with entities, concepts merge with "
        "concepts. **Never merge an entity into a concept or vice versa.**\n\n"
        "### Merge criteria — ALL must be true:\n"
        "1. The new item and the candidate page refer to the **same real-world thing** (same "
        "person, same organization, same specific concept).\n"
        "2. The match is a **name variation**: abbreviation ↔ full name, translation, or "
        "minor spelling difference.\n\n"
        "### Examples of CORRECT merges:\n"
        "- \"Acme Corp\" → \"Acme Corporation\" (same company, abbreviation)\n"
        "- \"RAG\" → \"Retrieval-Augmented Generation\" (same concept, acronym)\n"
        "- \"苹果公司\" → \"Apple Inc.\" (same entity, translation)\n\n"
        "### Examples of INCORRECT merges — do NOT merge these:\n"
        "- \"Hunyuan Model\" → \"Qwen Model\" (competing products in the same category are "
        "DIFFERENT entities, do not merge them)\n"
        "- \"iPhone 15\" → \"Huawei Mate 60\" (different specific instances in the same "
        "category)\n"
        "- \"GPT-4\" → \"GPT-3.5\" (different versions of a product are distinct entities)\n"
        "- \"AI Safety\" → \"Content Review Mechanism\" (related topics, but different "
        "concepts)\n"
        "- \"居民身份证 / Resident ID Card\" → \"工作居住证 / Work Residence Permit\" (both "
        "are government-issued documents but completely different credentials)\n"
        "- \"驾驶证 / Driver's License\" → \"行驶证 / Vehicle Registration\" (both are "
        "car-related certificates but different documents)\n"
        "- \"学位证 / Degree Certificate\" → \"毕业证 / Graduation Certificate\" (both "
        "educational documents but distinct)\n\n"
        "### Key principle: **related ≠ same**. Two items sharing a few characters in their "
        "name, or belonging to the same domain / document family / industry, is NOT a reason "
        "to merge. **ABSOLUTELY DO NOT** merge different products, different companies, "
        "different versions, or different certificates/documents just because they belong to "
        "the same category. When in doubt, do NOT merge. It is far better to have two "
        "separate pages for the same thing than to wrongly merge two different things.\n\n"
        "Write ALL reasoning internally; do not output explanations.\n\n"
        "Return a JSON object with a \"merges\" map. The key is the NEW item's slug, the "
        "value is the EXISTING page's slug that it should merge into. Only include items "
        "where you are highly confident they are the same thing.\n\n"
        "If no items match any existing pages, return: {{\"merges\": {{}}}}\n\n"
        "### JSON Formatting Rules\n"
        "- **CRITICAL**: Do NOT use literal newline characters inside JSON string values. If "
        "you need a newline in a string, you MUST use the escaped sequence \\n.\n"
        "</instructions>\n\n"
        "Output ONLY valid JSON. Example:\n"
        "{{\"merges\": {{\"entity/acme-corporation\": \"entity/acme-corp\", "
        "\"concept/rag\": \"concept/retrieval-augmented-generation\"}}}}"
    ),

    # Taxonomy：批级目录规划（一次调用整批同树，feed-forward 收敛）
    # 移植自 WeKnora WikiTaxonomyPlanPrompt
    "wiki_taxonomy_plan_user": (
        "You are organizing a wiki knowledge base into a navigation directory. Assign each "
        "item below to a directory path (category) so the whole set lands on ONE coherent "
        "tree.\n\n"
        "<existing_folders>\n{existing_taxonomy}\n</existing_folders>\n\n"
        "<items>\n{items}\n</items>\n\n"
        "<instructions>\n"
        "For every item, output a category path: an array of folder labels from broad to "
        "narrow (at most 2 levels). The category classifies WHAT the item fundamentally IS "
        "(the stable library \"shelf\" it always sits on), never the role it plays in one "
        "document.\n\n"
        "How to choose a path for each item:\n"
        "1. If an existing folder in <existing_folders> fits, REUSE its EXACT label "
        "(character-for-character). Do NOT invent a synonym folder (e.g. do NOT create "
        "\"春节习俗\" when \"春节 / 传统习俗\" already fits).\n"
        "2. If NO existing folder fits, CREATE a new, broad, durable folder for it (e.g. an "
        "organization → \"组织\", a legal idea → \"法律概念\", a place → \"地点\"). The "
        "directory does not have to stay small — most items DO have a natural home, so coin "
        "a sensible top-level folder rather than leaving them unfiled. Group items of the "
        "SAME kind under the SAME new folder so the tree stays coherent.\n"
        "3. Only give an empty path [] when an item genuinely belongs to NO durable subject "
        "at all. This must be RARE. The absence of a matching existing folder is NOT a "
        "reason for []; create a folder instead.\n\n"
        "Other rules:\n"
        "- Group items of the SAME kind under the SAME folder at the SAME depth. Do not file "
        "one equivalent item a level deeper than its siblings — pick one consistent depth "
        "for equivalent items.\n"
        "- Prefer a single broad top-level folder; add a second level only for a genuinely "
        "durable sub-domain shared by several items.\n"
        "- Do NOT use the item type (\"entity\"/\"concept\") as a folder. Do NOT put slashes "
        "inside a single label.\n"
        "- Every item slug in <items> MUST appear exactly once in the output.\n"
        "- Write ALL folder labels in {language}.\n\n"
        "### JSON Formatting Rules\n"
        "- Output ONLY valid JSON, no preamble.\n"
        "- Do NOT use literal newlines inside JSON string values.\n"
        "</instructions>\n\n"
        "Output format:\n"
        "{{\n"
        "  \"assignments\": [\n"
        "    {{\"slug\": \"entity/zhang-san\", \"path\": [\"人物\"]}},\n"
        "    {{\"slug\": \"concept/spring-festival\", \"path\": [\"节日\", \"传统节日\"]}}\n"
        "  ]\n"
        "}}"
    ),

    # Index intro 首建（对齐 WeKnora WikiIndexIntroPrompt）：基于页面摘要
    # 生成知识库简介
    "wiki_index_intro_user": (
        "You are writing a short introduction for a wiki knowledge base, based on the "
        "summaries of its pages below.\n\n"
        "<page_summaries>\n{summaries}\n</page_summaries>\n\n"
        "<instructions>\n"
        "Write a 2-4 paragraph introduction in {language} describing what this knowledge "
        "base covers, its main topics, and what a reader can find here. Ground every claim "
        "in the summaries above — do NOT invent topics that are not represented. Do NOT "
        "list the pages one by one (the directory listing is rendered separately).\n\n"
        "The first line must be: SUMMARY: {{one sentence, 15-40 words}}\n"
        "</instructions>\n\n"
        "Output the SUMMARY line first, then the introduction. No other preamble."
    ),

    # Index intro 增量更新（对齐 WeKnora WikiIndexIntroUpdatePrompt）
    "wiki_index_intro_update_user": (
        "You are maintaining the introduction of a wiki knowledge base. Below are the "
        "current introduction and a description of what recently changed.\n\n"
        "<current_intro>\n{existing_intro}\n</current_intro>\n\n"
        "<recent_changes>\n{changes}\n</recent_changes>\n\n"
        "<instructions>\n"
        "Update the introduction so it stays accurate in {language}. Keep it concise "
        "(2-4 paragraphs). Preserve existing wording where it is still accurate; adjust "
        "only what the changes require. Do NOT list pages one by one.\n\n"
        "The first line must be: SUMMARY: {{one sentence, 15-40 words}}\n"
        "</instructions>\n\n"
        "Output the SUMMARY line first, then the updated introduction. No other preamble."
    ),
}
